[package]
name = "stacktracer"
description = "Dump stack traces for native processes using ptrace and libunwind"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]

[dependencies]
errno = "*"
failure = "*"
libc = "*"
elf = "*"
rustc-demangle = "*"
clap = "*"
